name: your_project_name
description: A new Flutter project.

# Specify Flutter SDK version
environment:
  sdk: ">=3.5.0 <4.0.0"

# Dependencies
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

# Development dependencies
dev_dependencies:
  flutter_test:
    sdk: flutter

# Flutter specific configurations
flutter:
  uses-material-design: true
  assets:
    - assets/data.json
    - assets/profile.png
    - assets/imag1.png
    - assets/imag2.png
    - assets/imag3.png
    - assets/imag4.png
    - assets/imag5.png
    - assets/HomeCard.png
